# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jen < Formula
  desc "Jen is a CLI tool for scaffolding new microservices based on Go templates, onboarding them with your CI/CD and infra, and augmenting them with your DevOps scripts for their entire life-time."
  homepage "https://github.com/silphid/jen"
  version "0.2.17"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/silphid/jen/releases/download/v0.2.17/jen_0.2.17_darwin_x86_64.tar.gz"
    sha256 "7be2ce0ac09b91bb1c4509cfc955aca98b731b861b3fe8766aa8819bdd812adc"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/silphid/jen/releases/download/v0.2.17/jen_0.2.17_darwin_arm64.tar.gz"
    sha256 "51d7e5fdb5eb9667ef8f8b9e9ffa4ec34bfcf0a5682c4366885d7833b3570070"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/silphid/jen/releases/download/v0.2.17/jen_0.2.17_linux_x86_64.tar.gz"
    sha256 "b07076bbce998f5fb5e7f239122924a03c59a7dc39f8cc5180fb19e8f655ae55"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/silphid/jen/releases/download/v0.2.17/jen_0.2.17_linux_arm64.tar.gz"
    sha256 "2da116f5c1e8c320b775cd8acf7d1d3c7a98265e4cabdfe6eeedcda56b5f7a1d"
  end

  def install
    bin.install "jen"
  end
end
